[package]
name = "baserow-client"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
serde_json =  { workspace = true }
serde = { workspace = true }
snafu =  { workspace = true }
reqwest =  { workspace = true }
tokio =  { workspace = true }
url = "2.5.4"
http = "1.3.1"
